In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [2]:
x = np.arange(10).reshape(-1, 1)
y = np.array([0, 1, 1, 0, 1, 1, 1, 1, 1, 1])
print(x)
print(y)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[0 1 1 0 1 1 1 1 1 1]


In [3]:
model = LogisticRegression(solver='liblinear', C=10.0, random_state=0)
print(model.fit(x, y))

LogisticRegression(C=10.0, random_state=0, solver='liblinear')


In [4]:
p_pred = model.predict_proba(x)
y_pred = model.predict(x)
score_ = model.score(x, y)
conf_m = confusion_matrix(y, y_pred)
report = classification_report(y, y_pred)

In [5]:
print(report)

              precision    recall  f1-score   support

           0       1.00      0.50      0.67         2
           1       0.89      1.00      0.94         8

    accuracy                           0.90        10
   macro avg       0.94      0.75      0.80        10
weighted avg       0.91      0.90      0.89        10



In [6]:
print(score_)

0.9


In [7]:
print(conf_m)

[[1 1]
 [0 8]]


In [8]:
print(p_pred)

[[0.6495258  0.3504742 ]
 [0.49110886 0.50889114]
 [0.33445763 0.66554237]
 [0.2074088  0.7925912 ]
 [0.1199251  0.8800749 ]
 [0.0662568  0.9337432 ]
 [0.03563343 0.96436657]
 [0.01887779 0.98112221]
 [0.00991998 0.99008002]
 [0.00519031 0.99480969]]


In [9]:
print(y_pred)

[0 1 1 1 1 1 1 1 1 1]


In [10]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [11]:
df=pd.read_csv("D:\Data for ML\diabetes.csv")

In [12]:
X=df.iloc[:,:8].values
print(X)

[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]


In [13]:
Y=df["Outcome"].values
X_train, X_test, y_train, y_test=train_test_split(X, Y, test_size=0.3, random_state=100)

In [14]:
model = LogisticRegression(solver='liblinear', C=9.0, random_state=100)
print(model.fit(X_train, y_train))

LogisticRegression(C=9.0, random_state=100, solver='liblinear')


In [15]:
P_pred = model.predict_proba(X_train)
Y_pred = model.predict(X_train)
score_ = model.score(X_train, y_train)
conf_m = confusion_matrix(y_train, Y_pred)
report = classification_report(y_train, Y_pred)

In [16]:
print(y_train)

[1 0 1 1 0 1 1 0 0 0 1 1 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0
 0 1 1 1 1 0 0 0 0 0 1 1 0 0 0 1 1 1 0 0 1 0 0 1 0 0 1 0 0 0 1 1 1 1 0 0 0
 1 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 1 1 1 1 0 0 1 1 0 1 1 0 1 1 1 0 0
 0 0 1 0 0 1 0 0 1 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 1 0 1 0 0 1 1 0 0
 0 0 1 0 1 1 0 1 0 0 1 1 1 0 1 0 0 1 0 0 0 0 1 0 1 1 0 0 1 1 0 1 1 1 0 1 1
 1 0 0 0 0 0 0 1 1 1 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1
 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 1 0 0 0 1 1 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1
 1 0 0 0 0 0 0 1 0 0 0 0 1 1 1 1 1 1 1 0 1 1 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0
 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1 1
 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0
 0 0 0 1 0 1 1 1 0 0 0 1 0 0 0 0 1 1 0 1 1 0 1 0 0 1 0 1 0 0 0 0 1 0 0 0 1
 0 0 0 0 0 1 0 1 0 0 0 0 1 0 1 1 0 0 0 0 0 1 1 1 0 0 0 1 0 0 1 1 1 1 0 0 0
 0 0 1 0 1 0 1 0 0 0 1 0 

In [17]:
print(Y_pred)

[1 0 1 0 0 0 1 0 0 0 0 0 1 0 1 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1
 0 1 1 0 1 0 0 0 1 1 1 0 0 0 1 1 1 0 0 0 1 0 0 1 0 0 0 0 0 0 1 1 1 1 0 0 0
 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 1 1 0 1 1 0 1 0 0 0 1 0 0 1 0 0 0 0
 0 0 1 0 0 1 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 1 0 0 1 0 0 1 0 1
 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 1 1
 1 0 0 1 0 0 0 1 1 1 0 0 1 0 1 0 1 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 1 1 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 1 0 0 0 1 0 1 0 0 1
 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1
 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0
 0 0 0 1 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 1 1 1 0 0 1 0 0 1 1 1 1 0 0 0
 0 0 0 0 1 0 0 0 0 0 1 0 

In [18]:
print(report)

              precision    recall  f1-score   support

           0       0.81      0.90      0.85       350
           1       0.76      0.60      0.67       187

    accuracy                           0.80       537
   macro avg       0.79      0.75      0.76       537
weighted avg       0.79      0.80      0.79       537



In [19]:
print(conf_m)

[[315  35]
 [ 74 113]]


In [20]:
print(score_)

0.7970204841713222


In [21]:
print(P_pred)

[[0.12709136 0.87290864]
 [0.63759632 0.36240368]
 [0.37131264 0.62868736]
 ...
 [0.79047283 0.20952717]
 [0.89898852 0.10101148]
 [0.98166877 0.01833123]]


In [22]:
model = LogisticRegression(solver='liblinear', C=9.0, random_state=100)
print(model.fit(X_test, y_test))

LogisticRegression(C=9.0, random_state=100, solver='liblinear')


In [23]:
P_pred1 = model.predict_proba(X_test)
Y_pred1 = model.predict(X_test)
score_1 = model.score(X_test, y_test)
conf_m1 = confusion_matrix(y_test, Y_pred1)
report1 = classification_report(y_test, Y_pred1)

In [24]:
print(y_test)

[0 0 1 0 0 1 1 1 1 0 0 1 0 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 1 1 0 1 0 0 1 0 1
 0 1 1 1 0 1 0 0 1 0 0 1 0 0 0 1 1 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0
 1 0 0 1 0 1 0 0 1 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0
 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 1 1 0 1 1 0 0 0
 0 0 1 0 1 1 0 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0 1 0 0 0 1 0 0 0 0 0 1
 0 0 0 1 1 1 0 1 0 0 0 0 1 0 1 1 1 0 0 0 0 1 0 0 0 0 1 0 1 1 1 0 1 1 0 1 1
 0 0 0 0 1 0 1 0 0]


In [25]:
print(report1)

              precision    recall  f1-score   support

           0       0.77      0.89      0.83       150
           1       0.72      0.52      0.60        81

    accuracy                           0.76       231
   macro avg       0.75      0.71      0.72       231
weighted avg       0.76      0.76      0.75       231



In [26]:
print(score_1)

0.7619047619047619


In [27]:
print(P_pred1)

[[0.80788515 0.19211485]
 [0.89365132 0.10634868]
 [0.46684666 0.53315334]
 [0.8697075  0.1302925 ]
 [0.4677446  0.5322554 ]
 [0.3295974  0.6704026 ]
 [0.04367514 0.95632486]
 [0.84486281 0.15513719]
 [0.26863525 0.73136475]
 [0.74712659 0.25287341]
 [0.87530466 0.12469534]
 [0.17738533 0.82261467]
 [0.75569862 0.24430138]
 [0.77032628 0.22967372]
 [0.25289167 0.74710833]
 [0.59043401 0.40956599]
 [0.87836045 0.12163955]
 [0.78717573 0.21282427]
 [0.51068683 0.48931317]
 [0.74993446 0.25006554]
 [0.7305679  0.2694321 ]
 [0.95893188 0.04106812]
 [0.600521   0.399479  ]
 [0.12468558 0.87531442]
 [0.80341399 0.19658601]
 [0.26368287 0.73631713]
 [0.56000717 0.43999283]
 [0.70197554 0.29802446]
 [0.38956931 0.61043069]
 [0.55923684 0.44076316]
 [0.94621242 0.05378758]
 [0.09946691 0.90053309]
 [0.89988834 0.10011166]
 [0.51391311 0.48608689]
 [0.88882208 0.11117792]
 [0.81388963 0.18611037]
 [0.11508377 0.88491623]
 [0.94020381 0.05979619]
 [0.76599428 0.23400572]
 [0.56265703 0.43734297]


In [28]:
print(Y_pred1)

[0 0 1 0 1 1 1 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 1
 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 0 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 1 0 0 1 0
 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 1 0 1 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 1 0 1 0 1 0 0 0 0
 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 1 1 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0
 0 0 0 0 1 0 1 0 0]


In [29]:
print(conf_m1)

[[134  16]
 [ 39  42]]


In [30]:
y_pred = model.predict(X_test)
count_misclassified = (y_test != y_pred).sum()
print('Misclassified samples: {}'.format(count_misclassified))
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy: {:.2f}'.format(accuracy))

Misclassified samples: 55
Accuracy: 0.76


In [31]:
y_pred1 = model.predict(X_train)
count_misclassified = (y_train != y_pred1).sum()
print('Misclassified samples: {}'.format(count_misclassified))
accuracy = accuracy_score(y_train, y_pred1)
print('Accuracy: {:.2f}'.format(accuracy))

Misclassified samples: 120
Accuracy: 0.78
